accelerator: ddp
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
batch_size: 4096
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_dir: &id001 !!python/object/apply:pathlib.PosixPath
- data
- complete
default_root_dir: null
deterministic: false
distributed_backend: null
embedding_dim: 64
enable_pl_optimizer: null
exp_name: conv_lr1e2_bs4096_emb64_hid128_dot
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_val: 0
hidden_dim: 128
hparams: !!python/object:argparse.Namespace
  accelerator: ddp
  accumulate_grad_batches: 1
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  automatic_optimization: null
  batch_size: 4096
  benchmark: false
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  data_dir: *id001
  default_root_dir: null
  deterministic: false
  distributed_backend: null
  embedding_dim: 64
  enable_pl_optimizer: null
  exp_name: conv_lr1e2_bs4096_emb64_hid128_dot
  fast_dev_run: false
  flush_logs_every_n_steps: 100
  gpus: 1
  gradient_clip_val: 0
  hidden_dim: 128
  kernel_size: 3
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  logger: true
  lr: 0.01
  max_epochs: 2000
  max_steps: null
  min_epochs: 1
  min_steps: null
  move_metrics_to_cpu: false
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 2
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: 1
  reload_dataloaders_every_epoch: false
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: &id002 !!python/name:pytorch_lightning.utilities.argparse_utils._gpus_arg_default ''
  track_grad_norm: -1
  truncated_bptt_steps: null
  val_check_interval: 0.25
  weights_save_path: null
  weights_summary: top
kernel_size: 3
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.01
max_epochs: 2000
max_steps: null
min_epochs: 1
min_steps: null
move_metrics_to_cpu: false
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
sync_batchnorm: false
terminate_on_nan: false
tpu_cores: *id002
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 0.25
weights_save_path: null
weights_summary: top
